import { Link } from "react-router-dom";
import { User, MessageCircle, Home, FileText } from "lucide-react";

export default function Dashboard() {
  return (
    <main className="min-h-screen bg-[#eef2f7] flex justify-center">
      <div className="w-full max-w-[430px] min-h-screen bg-[#eef2f7] px-5 pt-8 pb-24">

        <div className="flex items-center justify-between mb-5">
          <div>
            <p className="text-xl font-bold text-[#10233f]">
              Hi Chioma, 👋
            </p>
          </div>

          <div className="w-10 h-10 rounded-xl bg-[#08758b] text-white flex items-center justify-center font-bold">
            CO
          </div>
        </div>

        <div className="grid grid-cols-3 gap-3 mb-2">
          <Stat number="2" text="roles matched" />
          <Stat number="3" text="skills to learn" />
          <Stat number="24h" text="since you started" />
        </div>

        {/* Roadmap */}
        <div className="rounded-3xl bg-[#082653] text-white p-5 mt-2">
          <p className="text-sm font-semibold text-cyan-400">
            GENERATED BY GenAI 6.0
          </p>

          <h2 className="text-lg font-bold mt-1">
            Your targeted career roadmaps
          </h2>

          <div className="grid grid-cols-2 gap-5 mt-4 text-xs">
            <div>
              <p className="font-semibold mb-2">🎯 Target roles</p>
              <p className="text-slate-300 mb-3">• Junior Frontend Developer</p>
              <p className="text-slate-300">• UI/UX Implementation Intern</p>
            </div>

            <div>
              <p className="font-semibold mb-2">📕 Skills next</p>
              <p className="text-slate-300 mb-3">• HTML5 & CSS Flexbox</p>
              <p className="text-slate-300">• JavaScript ES6 Basics</p>
            </div>
          </div>

          <div className="border-t border-slate-500/50 mt-5 pt-4">
            <p className="text-xs text-slate-300">Skill Plan Progress</p>

            <div className="flex items-center gap-3 mt-1">
              <div className="w-10 h-10 rounded-full border-4 border-cyan-400 border-r-slate-500" />
              <p className="font-bold">20% complete</p>
            </div>
          </div>
        </div>

        {/* CV */}
        <div className="bg-white rounded-2xl border border-slate-300 p-4 mt-3 flex items-center justify-between">
          <div>
            <p className="font-semibold text-[#10233f]">
              📄 CV draft ready
            </p>
            <p className="text-xs text-slate-400">
              Structured for Junior Frontend Developer Roles
            </p>
          </div>

          <Link
            to="/cv"
            className="text-xs border border-slate-300 rounded-lg px-3 py-2 text-slate-500"
          >
            View
          </Link>
        </div>

        {/* Jobs */}
        <div className="mt-5">
          <h3 className="font-semibold text-[#10233f] mb-2">
            Job Recommendation
          </h3>

          <div className="flex gap-2 overflow-hidden">
            <Job title="Junior Web Developer" company="Magma Corp" />
            <Job title="Frontend Intern" company="Lex Corp" />
            <Job title="Junior Developer" company="Magma Corp" />
          </div>
        </div>

        {/* Bottom nav */}
        <div className="fixed bottom-5 left-1/2 -translate-x-1/2 w-[90%] max-w-[390px] bg-white border border-slate-300 rounded-full px-7 py-3 flex justify-between shadow-lg">
          <Home size={20} className="text-[#082653]" />
          <Link to="/chat">
            <MessageCircle size={20} className="text-slate-500" />
          </Link>
          <Link to="/cv">
            <User size={20} className="text-slate-500" />
          </Link>
        </div>
      </div>
    </main>
  );
}

function Stat({ number, text }) {
  return (
    <div className="bg-white border border-slate-300 rounded-xl py-3 text-center">
      <p className="font-bold text-[#10233f]">{number}</p>
      <p className="text-[10px] text-slate-500">{text}</p>
    </div>
  );
}

function Job({ title, company }) {
  return (
    <div className="min-w-[120px] bg-white border border-slate-300 rounded-xl p-3">
      <p className="font-semibold text-xs text-[#10233f]">{title}</p>
      <p className="text-[10px] text-slate-500 mt-1">{company}</p>
      <p className="text-[10px] text-slate-400 mt-2">Remote</p>
      <button className="bg-[#082653] text-white text-[10px] rounded-full px-3 py-1 mt-2">
        Apply
      </button>
    </div>
  );
}